cache:
    pipeline: [~/.npm]

shared:
    image: node:12

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - install: npm ci
            - test: npm test

    publish:
        requires: main
        template: screwdriver-cd/semantic-release
        secrets:
            # Publishing to NPM
            - NPM_TOKEN
            # Github token to push tags to Git
            - GH_TOKEN